wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    framework: ignite
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.6.13
    start_time: 1636119297
    t:
      1:
      - 1
      - 10
      2:
      - 1
      - 10
      3:
      - 1
      - 2
      - 13
      - 15
      - 16
      4: 3.6.13
      5: 0.12.6
      8:
      - 1
      - 5
angle_max:
  desc: null
  value: 2*np.pi
biasOnoise:
  desc: null
  value: 0
delta_z:
  desc: null
  value: 0.004
device:
  desc: null
  value: cuda:0
energy_type:
  desc: null
  value: passive
epochs:
  desc: null
  value: 50
exp_name:
  desc: null
  value: Error Quantification Check2021-11-05 09:34:57.184600
get_dataloaders:
  desc: null
  value: get_qpm_dataloaders
img_size:
  desc: null
  value: 32
in_dist:
  desc: null
  value: 0.004
int_ramp:
  desc: null
  value: 'no'
lambda_:
  desc: null
  value: 0.00075
learn_type:
  desc: null
  value: both
learning_rate:
  desc: null
  value: 0.01
log_wandb:
  desc: null
  value: true
loss_func:
  desc: null
  value: BerHu('mean',0.95).to(device)
model:
  desc: null
  value: d2nnASwWindow
n_layers:
  desc: null
  value: 8
neuron_size:
  desc: null
  value: 0.0003
out_dist:
  desc: null
  value: 0.007
photon_count:
  desc: null
  value: 1
save_results_local:
  desc: null
  value: false
shrink_factor:
  desc: null
  value: 1
task_type:
  desc: null
  value: phase2amp
testing:
  desc: null
  value: false
torch_seed:
  desc: null
  value: 10
train_batch_size:
  desc: null
  value: 32
unwrapped_phase:
  desc: null
  value: false
window_size:
  desc: null
  value: 4
